<a href="https://colab.research.google.com/github/fluffymouses/fluffymouses/blob/main/lab3/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 3

##Обработка пропущенных значений

Обработайте пропущенные значения:


* Удалите пропущенные значения
* Заполните при помощи медианы, среднего для числовых значений
* Заполните при помощи моды для категориальных значений
* Интерполируйте
Выведите статистку после каждого метода и объясните

In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

In [3]:

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/crimes_against_women_2001-2014.csv')
df

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0

In [5]:
#Удаление
df_cleaned = df.dropna()

df_cleaned

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
18,18,ANDHRA PRADESH,RANGA REDDY,2001,72,83,37,113,55,421,7
28,28,ANDHRA PRADESH,TOTAL,2001,871,765,420,3544,2271,5791,7
77,77,BIHAR,BETTIAH,2001,20,23,17,23,0,54,8
97,97,BIHAR,MUZAFFARPUR,2001,73,25,69,81,0,141,6
101,101,BIHAR,NAWADAH,2001,15,1,17,7,0,13,1
...,...,...,...,...,...,...,...,...,...,...,...
10291,451,Maharashtra,Total District(s),2014,3438,2457,279,10001,1575,7696,1
10629,789,West Bengal,Kolkata,2014,36,220,12,577,286,1141,2
10632,792,West Bengal,Nadia,2014,106,336,50,181,8,1827,1
10634,794,West Bengal,Purab Medinipur,2014,53,208,27,157,6,974,1
10640,800,West Bengal,Total District(s),2014,1466,4976,501,5670,543,23278,4

In [9]:
import pandas as pd
import numpy as np
def create_holes(dataframe, column_name, hole_percentage = 10):

    if hole_percentage < 0 or hole_percentage > 100:
        raise ValueError("Процент дырявости должен быть в диапазоне от 0 до 100.")

    dataframe_with_holes = dataframe.copy()
    num_holes = int(len(dataframe) * (hole_percentage / 100))
    hole_indices = np.random.choice(len(dataframe), num_holes, replace=False)
    dataframe_with_holes.loc[hole_indices, column_name] = np.nan

    return dataframe_with_holes


df = create_holes(df, 'holes')

In [11]:
#Заполнение при помощи медианы
df_filled_mean = df.fillna(df.mean())

df_filled_mean

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,column,holes
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0,NaN,NaN
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0,NaN,NaN
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0,NaN,NaN
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0,NaN,NaN
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0,NaN,NaN
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0,NaN,NaN
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0,NaN,NaN
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0,NaN,NaN
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0,NaN,NaN

In [13]:
#Заполнение при помощи среднего
df_filled_median = df.fillna(df.median())

df_filled_median

<ipython-input-13-54d0f788a016>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_median = df.fillna(df.median())

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,column,holes
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0,NaN,NaN
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0,NaN,NaN
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0,NaN,NaN
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0,NaN,NaN
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0,NaN,NaN
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0,NaN,NaN
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0,NaN,NaN
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0,NaN,NaN
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0,NaN,NaN

In [12]:
#Заполнение при помощи моды
df_filled_mode = df.fillna(df["Dowry Deaths"].mode()[0])
"""
Мода возвращает объект Series, так как
значений моды может быть несколько
"""
df_filled_mode

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,column,holes
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0,0.0,0.0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0,0.0,0.0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0,0.0,0.0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0,0.0,0.0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0,0.0,0.0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0,0.0,0.0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0,0.0,0.0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0,0.0,0.0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0,0.0,0.0

In [14]:
#Заполнение при помощи интерполяции
df_interpolated = df.interpolate()

df_interpolated

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls,column,holes
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0,NaN,NaN
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0,NaN,NaN
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0,NaN,NaN
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0,NaN,NaN
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0,NaN,NaN
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0,NaN,NaN
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0,NaN,NaN
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0,NaN,NaN
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0,NaN,NaN

**Объясните**

##Поиск выбросов и аномалий

**Те, кто выполняет задания со * делают поиск выбросов с помощью написанного ранее класса**

Найти выбросы по числовой переменной (использовать метод основанный на среднем и на межквартильном размахе). Объясните результат

Вывести статистику с выбросами и без. Сравните и объясните результат

In [ ]:
#Методом среднего

In [ ]:
#При помощи межквартильного размаха

In [ ]:
#Статистика и объяснение

**Объяснения**

##Дубликаты

Проверьте датафрейм на дубликаты и удалите их, если дублей нет - создайте.

In [ ]:
#Проверка на дубли

In [ ]:
#Удаление дублей

## Преобразование признаков

Масштабируйте числовые признаки через MinMaxScaler, StandardScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Creating instances
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

Масштабируйте категориальные признаки через OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

##Задание для гениев*


Реализовать расчет корреляции Спирмана

In [ ]:
#Функция по расчету тут

In [ ]:
#Пример использования тут и объяснение принципа работы

###Пример реализации

In [ ]:
import pandas as pd
import numpy as np


def corr_pearson(column_1, column_2):
  cov = np.cov(column_1, column_2)
  return cov/(column_1.std() * column_2.std())

In [ ]:
data = {
    'Рост': [170, 155, 180, 162, 175],
    'Вес': [65, 50, 75, 55, 70]
}
df = pd.DataFrame(data)
df

   Рост  Вес
0   170   65
1   155   50
2   180   75
3   162   55
4   175   70

In [ ]:
corr_pearson(df["Рост"], df["Вес"])

array([[0.96593129, 0.99674864],
       [0.99674864, 1.03527033]])